export const EnvironmentVariables = {
  KAFKA_NOTI_EMAIL_VERIFICATION_TOPIC: 'KAFKA_NOTI_EMAIL_VERIFICATION_TOPIC',
  KAFKA_NOTI_EMAIL_VERIFICATION_TEMPLATE_ID: 'KAFKA_NOTI_EMAIL_VERIFICATION_TEMPLATE_ID',
  KAFKA_BROKERS: 'KAFKA_BROKERS',
  KAFKA_CLIENT_ID: 'KAFKA_CLIENT_ID',
  KAFKA_CONSUMER_GROUP_ID: 'KAFKA_CONSUMER_GROUP_ID',
};
